# Generated by Django 5.2.10 on 2026-02-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0037_essay_student_alter_essay_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='admin', max_length=150),
            preserve_default=False,
        ),
    ]
