# Generated by Django 5.2.10 on 2026-02-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0039_assignment_rating_assignment_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentreg',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
