# Generated by Django 5.2.10 on 2026-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0040_studentreg_batch_studentreg_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
