# Generated by Django 5.2.10 on 2026-03-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0041_login_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='current_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='mark',
        ),
        migrations.AddField(
            model_name='assignment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='omr',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='omr',
            name='mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='omr',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='omr',
            name='sem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.login'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduVance.assignmentquestion'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
