# Generated by Django 5.2.10 on 2026-03-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0042_rename_current_date_assignment_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='uploaded_at',
            new_name='current_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='module',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='omr',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='omr',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='omr',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='omr',
            name='sem',
        ),
        migrations.AddField(
            model_name='assignment',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduVance.studentreg'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EduVance.assignmentquestion'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
