# Generated by Django 4.2.29 on 2026-03-04 22:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0044_alter_login_email_alter_teacherreg_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
    ]
