# Generated by Django 4.2.29 on 2026-03-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0045_alter_assignment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='rating',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
