# Generated by Django 4.2.29 on 2026-03-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduVance', '0046_alter_assignment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='admno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='contactno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='department',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='dob',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
